# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff392c50d7f8563d5e18f352671b23d5bc5d173d30a368fa79560607cf74724ccccdc1f0b40ad5423078788350adfcfbf591fd6645475811714963dea40057b4

test:
  secret_key_base: de9033af7e0a2205f281ed7f311eb1d8567f8728e555f7ca4bccc26834c22d90a7369101e4dccabbea55649d99245f727da4680775fa8f9bfb56985cfaeef304

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
